# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 05 * * *"
    - cron: "0 11 * * *"
    - cron: "0 17 * * *"
    - cron: "0 21 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Run
      run: go run main.go

    - name: Move files
      run: |
        mkdir ./public
        cp ./index.html ./public/
        mv *.png ./public/
      # If you have non-minimal setup with some assets and separate html/js files,
      # provide --output=<output-file> option for `elm make` and remove this step

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: vreme.dz0ny.dev
